import mongoose from "mongoose";
const blogPostSchema = new mongoose.Schema({
  authorEmail: { type: String },
  authorName: { type: String },
  authorMail: { type: String },
  commentCount: { type: Number },
  commentStatus: { type: String },
  guid: { type: String, required: true },
  menuOrder: { type: Number },
  pingStatus: { type: String },
  pinged: { type: String },
  postAuthor: { type: String },
  postContent: { type: String, required: true },
  postContentFiltered: { type: String, required: true },
  postExcerpt: { type: String },
  postMimeType: { type: String },
  postName: { type: String, required: true },
  postParent: { type: Number },
  postPassword: { type: String },
  postStatus: { type: String },
  postStatusSyndication: { type: String, required: true },
  postTitle: { type: String, required: true },
  postType: { type: String, required: true },
  schedulePostDate: { type: Date, required: true },
  siteId: { type: mongoose.Schema.Types.ObjectId, ref: "Site" },
  siteType: { type: String, required: true },
  toPing: { type: String },
  postDate: { type: Date },
  postDataGmt: { type: Date },
  postModified: { type: Date },
  postModifiedGmt: { type: Date },
  websiteUrl: { type: String },
  postMeta: { type: mongoose.Schema.Types.ObjectId, ref: "PostMeta" },
});
const BlogPost = mongoose.model("BlogPost", blogPostSchema);
export default BlogPost;
